# Generated by Django 5.2.8 on 2025-11-09 19:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "width",
                    models.FloatField(
                        help_text="Stage width in meters",
                        validators=[django.core.validators.MinValueValidator(1.0)],
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        help_text="Stage height in meters",
                        validators=[django.core.validators.MinValueValidator(1.0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("paper_target", "Paper Target"),
                            ("steel_target", "Steel Target"),
                            ("popper", "Popper"),
                            ("plate_rack", "Plate Rack"),
                            ("no_shoot", "No Shoot Target"),
                            ("barrier", "Barrier"),
                            ("wall", "Wall"),
                            ("shooting_box", "Shooting Box"),
                            ("start_position", "Start Position"),
                            ("table", "Table"),
                            ("barrel", "Barrel"),
                            ("door", "Door"),
                            ("window", "Window"),
                        ],
                        max_length=50,
                    ),
                ),
                ("position_x", models.FloatField(help_text="X position in meters")),
                ("position_y", models.FloatField(help_text="Y position in meters")),
                (
                    "rotation",
                    models.FloatField(default=0, help_text="Rotation in degrees"),
                ),
                (
                    "width",
                    models.FloatField(
                        default=0.5,
                        help_text="Item width in meters",
                        validators=[django.core.validators.MinValueValidator(0.1)],
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        default=0.5,
                        help_text="Item height in meters",
                        validators=[django.core.validators.MinValueValidator(0.1)],
                    ),
                ),
                (
                    "custom_ammo_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Override default ammo count for this item",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="stages.stage",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
