# Generated by Django 4.2.26 on 2025-11-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="is_public",
            field=models.BooleanField(
                default=True, help_text="Make this stage visible to all users"
            ),
        ),
    ]
