# Generated by Django 4.2.26 on 2025-11-10 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stages", "0002_stage_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="bullet_trap_sides",
            field=models.CharField(
                choices=[
                    ("north", "North (Downrange)"),
                    ("south", "South (Uprange)"),
                    ("east", "East (Right)"),
                    ("west", "West (Left)"),
                    ("north-east", "North-East (Corner)"),
                    ("north-west", "North-West (Corner)"),
                    ("south-east", "South-East (Corner)"),
                    ("south-west", "South-West (Corner)"),
                    ("east-west", "East-West (Both Sides)"),
                ],
                default="north",
                help_text="Where bullet traps are positioned on the stage",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stage",
            name="height",
            field=models.FloatField(
                help_text="Stage length (depth) in meters",
                validators=[django.core.validators.MinValueValidator(1.0)],
            ),
        ),
    ]
